spring:
  datasource:
    rcm-rdb:
      tenant:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://152.69.231.63:3306/mc_tenant?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull
        password: rcm-pwd01
        url: jdbc:mysql://152.69.231.63:3306/mc_tenant?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull
        username: rcm-client
        hibernate:
          cache:
            use_query_cache: true
            use_second_level_cache: true
            redisson:
              entity-adminSecurity:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
              query-adminSecurity:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
              entity-tenant:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
              query-tenant:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          hbm2ddl:
            auto: update
          show_sql: true
    rcm-mongo: # for override spring.data.mongodb.* values each at services
      tenant:
        connectionString: mongodb+srv://rcm-mongo-client:rcm-pwd@cluster0.gyh5s.mongodb.net/rcm-tenant?retryWrites=true&w=majority&connecttimeoutms=10000&sockettimeoutms=15000&waitqueuetimeoutms=3000&maxlifetimems=60000&maxlifetimems=120000&heartbeatfrequencyms=20000&ssl=true
        database: rcm-tenant
        username: rcm-mongo-client
        password: rcm-pwd
        retryWrite: true
        authSource: admin
  application:
    name: "micro-tenant"
  messages:
    basename: messages/tenant/messages,messages/cloud-common/messages,messages/common/messages
  kafka:
    consumer:
      group-id: kafka-tenant-consumer
      auto-offset-reset: latest

platform:
  config:
    microservice:
      tenant: true
    security:
      server: true
    tenant:
      name: "micro-tenant(from git - application)"

eureka:
  instance:
    intance-id: micro-tenant-instance
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

