spring:
  datasource:
    rcm-rdb:
      order:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://152.69.231.63:3306/mc_order?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull
        password: rcm-pwd01
        url: jdbc:mysql://152.69.231.63:3306/mc_order?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull
        username: rcm-client
        hibernate:
          cache:
            use_query_cache: true
            use_second_level_cache: true
            redisson:
              entity-order:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
              query-order:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
              entity-cart:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
              query-cart:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
              entity-wishlist:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
              query-wishlist:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
              entity-fulfillmentMessage:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
              query-fulfillmentMessage:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          hbm2ddl:
            auto: update
          show_sql: true
    rcm-mongo: # for override spring.data.mongodb.* values each at services
      order:
        connectionString: mongodb+srv://rcm-mongo-client:rcm-pwd@cluster0.gyh5s.mongodb.net/rcm-order?retryWrites=true&w=majority&connecttimeoutms=10000&sockettimeoutms=15000&waitqueuetimeoutms=3000&maxlifetimems=60000&maxlifetimems=120000&heartbeatfrequencyms=20000&ssl=true
        database: rcm-order
        username: rcm-mongo-client
        password: rcm-pwd
        retryWrite: true
        authSource: admin
  application:
    name: "micro-commerce-order"
  messages:
    basename: messages/order/messages,messages/cloud-common/messages,messages/common/messages

platform:
  config:
    microservice:
      catalog: true

eureka:
  instance:
    intance-id: micro-commerce-order-intance
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"